id: test-distributor
endpoints:
  storageSquid: http://squid-graphql-server:4352/graphql
  joystreamNodeWs: ws://joystream-node:9944/
directories:
  assets: /data
  cacheState: /cache
logs:
  file:
    level: debug
    path: /logs
    maxFiles: 30 # 30 days or 30 * 50 MB
    maxSize: 50485760 # 50 MB
  console:
    level: verbose
  # elastic:
  #   level: http
  #   endpoint: http://localhost:9200
  #   auth:
  #     username: username
  #     password: password
limits:
  storage: 250G
  maxConcurrentStorageNodeDownloads: 100
  maxConcurrentOutboundConnections: 300
  outboundRequestsTimeoutMs: 5000
  pendingDownloadTimeoutSec: 3600
  # shouldn't this be higher? or large files are not getting cached and always fetched from SP?
  maxCachedItemSize: 1G
intervals:
  saveCacheState: 60
  checkStorageNodeResponseTimes: 60
  cacheCleanup: 7200 # every 2h, cache cleanup currently is very heavy on QN
publicApi:
  port: 3334
operatorApi:
  port: 3335
  hmacSecret: change-this-secret
keys:
  # - suri: //Alice
  # - mnemonic: "escape naive annual throw tragic achieve grunt verify cram note harvest problem"
  #   type: ed25519
  - keyfile: "/keystore/distributor-role-key.json"
workerId: 0
